Pull from public connectedhomeip
This commit pulls the commit 1536ca20c5917578ca40ce509400e97b52751788
from public connectedhomeip master. The change is to bump the
promp-toolkit version to fix ptpyhon version update.
With this change the follwoing error from bootstrap.sh environment setup
will be fixed:
Failed to import module "pw_watch.watch" (ImportError: cannot import name
'OneStyleAndTextTuple' from 'prompt_toolkit.formatted_text'

Public connectehomeip commit:
commit 1536ca20c5917578ca40ce509400e97b52751788
Author: Andrei Litvin <andy314@gmail.com>
Date:   Wed Dec 13 13:27:16 2023 -0500

    Bump prompt-toolkit requirement to fix ptpython version update (#30987)

Signed-off-by: Maulik Jodhani <mjodhani@innophaseiot.com>